version: 1
services:
  - type: web
    name: url-shortener
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: "FLASK_ENV"
        value: "production"
    autoDeploy: true
